services:
    mybuilder.supervisor_bundle.annotation_supervisor_exporter:
        class: MyBuilder\Bundle\SupervisorBundle\Exporter\AnnotationSupervisorExporter
        public: true
        arguments:
            - "@annotation_reader"
            - "%mybuilder.supervisor_bundle.exporter_config%"

    # Ensure command is loaded within Symfony 4
    MyBuilder\Bundle\SupervisorBundle\Command\DumpCommand:
        arguments:
            - '@mybuilder.supervisor_bundle.annotation_supervisor_exporter'
        tags:
            - { name: 'console.command' }
