language: php

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 5.6
      env: SYMFONY_VERSION=3.3.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.1
      env: SYMFONY_VERSION=4.1.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*

before_script:
  - composer require symfony/console:${SYMFONY_VERSION}
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: bin/phpunit
